export const PortfolioData = {
    portfolio_name: "My Portfolio",
    balance: 0,
    balance_change_24h_percentage: '+ 0%',
    balance_change_24h : '+ $0.00',
    assets: [
        /*{
            id: 'bitcoin',
            logo: "https://s2.coinmarketcap.com/static/img/coins/64x64/1.png",
            name: "Bitcoin",
            ticker: "BTC",
            price: 47075.36,
            change_24h: 4.87,
            change_7d: 3.21,
            holdings: '0.12 BTC',
            holding_dollar: 739.81,
            avg_buy_price: 43918.43,
            profit_dollar: 101.98,
            profit_percentage: 12.98,
        },
        {
            id: 'hoge-finance',
            logo: "https://s2.coinmarketcap.com/static/img/coins/64x64/8438.png",
            name: "Hoge Finance",
            ticker: "HOGE",
            price: 2.06,
            change_24h: 36.87,
            change_7d: 18.15,
            holdings: '4,218,679 HOGE',
            holding_dollar: 715.81,
            avg_buy_price: 0.000148,
            profit_dollar: 88.98,
            profit_percentage: 24.98,
        },
        {
            id: 'ethereum',
            logo: "https://s2.coinmarketcap.com/static/img/coins/64x64/1027.png",
            name: "Ethereum",
            ticker: "ETH",
            price: 3841.06,
            change_24h: 8.61,
            change_7d: -12.98,
            holdings: '0.38 ETH',
            holding_dollar: 611.98,
            avg_buy_price: 2389.90,
            profit_dollar: -56.91,
            profit_percentage: -23.11,
        },*/
    ]
}